name: build-and-release
on:
  workflow_run:
    workflows: ["main-worklfow"]
    push:
      branches: [master]
    types: 
      - completed

env:
  IMAGE_NAME: github-actions-demo

jobs:
  # Push image to GitHub Packages.
  build-and-push-to-registry:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push        
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            $${{ github.repository }}:latest
            $${{ github.repository }}:1.0.0
          cache-to: type=gha,mode=max
          cache-from: type=gha